### ISSUE TITLE
 java URLs with io_uring question

### ISSUE THREAD

**Issue by xtuyaowu** [benravago/QueueIO#1]
hi benravago：
    There are plans to optimize java URLs with io_uring？thanks

regard

**Comment by benravago** [comment]
Sorry for the delay.

Are you asking about io_uring in HttpURLConnection or HttpClient implementation in the jdk?  I think the Loom project may be looking into something like that (see https://cr.openjdk.java.net/~rpressler/loom/loom/sol1_part1.html)

If you're asking about an http example, I had been planning to do that next but just got busy with some other stuff.
